---
- name: Install MySQL database
  apt: name={{ item }} state=present
  with_items:
    - mysql-client
    - mysql-server

- name: Bind address for public access
  lineinfile:
    path: "/etc/mysql/mysql.conf.d/mysqld.cnf"
    state: present
    regexp: "^bind-address.*="
    line: "bind-address=0.0.0.0"

- name: Start MySQL Service
  shell: service mysql start

- name: Create Database user
  mysql_user:
    login_unix_socket: /var/run/mysqld/mysqld.sock
    login_user: root
    login_password: ''
    name: "{{ db_user }}"
    password: "{{ db_password }}"
    priv: '*.*:ALL'
    host: '%'
    state: present
    check_implicit_admin: true

- name: Create Application Database
  mysql_db: 
    login_unix_socket: /var/run/mysqld/mysqld.sock
    login_user: root
    login_password: ''
    name: "{{ db_name }}" 
    state: present
    check_implicit_admin: true
