version: "3.9"
services:
   pivot:
      hostname: pivot
      image: mauricubo/ubuntu_ansible_sshd:1.0
      ports:
         - "2222:22"
      environment:
         - TZ="America/Lima"
      networks:
         ansible.lab:
            ipv4_address: 172.24.0.2
      volumes:
        - "./ansible_files:/home/ubuntu/ansible"
   ubuntu1:
      hostname: ubuntu1
      image: mauricubo/ubuntu_sshd:1.0
      ports:
         - "2223:22"
      networks:
         ansible.lab:
            ipv4_address: 172.24.0.3
   ubuntu2:
      hostname: ubuntu2
      image: mauricubo/ubuntu_sshd:1.0
      ports:
         - "2224:22"
      networks:
         ansible.lab:
            ipv4_address: 172.24.0.4
   ubuntu3:
      hostname: ubuntu3
      image: mauricubo/ubuntu_sshd:1.0
      ports:
         - "2225:22"
      networks:
         ansible.lab:
            ipv4_address: 172.24.0.5
      
networks:
   ansible.lab:
      name: ansible.lab
      driver: bridge
      ipam:
         config:
            -  subnet: 172.24.0.0/24
               gateway: 172.24.0.1