---
- name: Deploy a web application
  hosts: webservers
  tasks:
    - name: Install all required dependencies
      apt: name={{ item }} state=present
      with_items:
        - python3
        - python3-setuptools
        - python3-dev
        - build-essential
        - python3-pip
        - python3-pymysql

    - include_tasks: tasks/deploy_db.yaml
    - include_tasks: tasks/deploy_webserver.yaml