---
# CSV file
- name: Test Connectivity
  hosts: ubuntu1
  vars:
    ansible_ssh_common_args: '-o StrictHostKeyChecking=no'
    ansible_ssh_pass: "{{ lookup('csvfile', 'web_server', file='credentials.csv', delimiter=',') }}"
  tasks:
  - name: Print vars
    debug:
      msg: "Var {{ ansible_ssh_pass }}"

  - name: Ping target host
    ping:
      data: "Test {{ansible_ssh_pass}}"

# Ini file
- name: Test Connectivity 2
  hosts: ubuntu1
  vars:
    ansible_ssh_common_args: '-o StrictHostKeyChecking=no'
    ansible_ssh_pass: "{{ lookup('ini', 'password', file='credentials.ini', section='web_server') }}"
  tasks:
  - name: Print vars
    debug:
      msg: "Var {{ ansible_ssh_pass }}"

  - name: Ping target host
    ping:
      data: "Test {{ansible_ssh_pass}}"
