---
- name: Install Python Flask dependency
  pip:
    name: "{{ item }}"
    state: present
  with_items:
    - flask
    - flask-mysql

- name: Copy source code
  copy: src=app.py dest=/opt/app.py

- name: Set environment variable
  lineinfile:
    path: "/etc/environment"
    state: present
    regexp: "^{{ item.key }}="
    line: "{{ item.key }}={{ item.value}}"
  with_items: "{{ os_environment }}"

- name: Start Web Server
  shell: FLASK_APP=/opt/app.py nohup flask run --host=0.0.0.0 &